import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
const api = async (path, options = {}) => { const token = localStorage.getItem("token"); const response = await fetch(`/api${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: "Bearer " + token } : {}), ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw Error(data.error || "Request failed"); return data; };
import { BrowserRouter, useNavigate, Routes, Route, Link, useParams } from "react-router-dom";
import { io as socketIO } from "socket.io-client";
import "./styles.css";
function Nav() { return <nav><Link to="/" className="brand">Evently</Link><span /><Link to="/events">Events</Link><Link to="/bookings">My bookings</Link>{localStorage.token ? <button onClick={() => { localStorage.clear(); location.href = "/"; }}>Logout</button> : <Link to="/login">Login</Link>}</nav>; }
function Events() { const [events, setEvents] = useState([]), [q, setQ] = useState(""); useEffect(() => { api(`/events${q ? `?search=${encodeURIComponent(q)}` : ""}`).then(x => setEvents(x.events || x)); }, [q]); return <main><div className="hero"><h1>Discover your next experience</h1><p>Find and book memorable events.</p><input placeholder="Search events..." value={q} onChange={e => setQ(e.target.value)} /></div><section className="grid">{events.map(e => <article className="card" key={e._id}><div className="cover">🎟️</div><h3>{e.title}</h3><p>{e.venue} · {new Date(e.startAt).toLocaleString()}</p><p>{e.availableSeats} seats available</p><Link className="btn" to={`/events/${e._id}`}>View details</Link></article>)}</section></main>; }
function EventPage() { const { id } = useParams(), [event, setEvent] = useState(), [message, setMessage] = useState(""); useEffect(() => { api(`/events/${id}`).then(setEvent); const socket = socketIO(); socket.emit("join:event", id); socket.on("seats:update", x => setEvent(e => e ? { ...e, availableSeats: x.availableSeats } : e)); return () => socket.disconnect(); }, [id]); if (!event) return <main>Loading...</main>; const book = () => api(`/events/${id}/book`, { method: "POST", body: JSON.stringify({ quantity: 1 }) }).then(b => setMessage(`Booking ${b.status}!`)).catch(e => setMessage(e.message)); const wait = () => api(`/events/${id}/waitlist`, { method: "POST", body: JSON.stringify({ quantity: 1 }) }).then(() => setMessage("Added to waitlist")).catch(e => setMessage(e.message)); return <main className="detail"><div className="cover big">🎟️</div><h1>{event.title}</h1><p>{event.description}</p><p><b>{event.venue}</b> · {new Date(event.startAt).toLocaleString()}</p><p>{event.availableSeats} seats available</p><button className="btn" onClick={book}>Book now</button> <button className="btn" onClick={wait}>Join waitlist</button>{message && <div className="notice">{message}</div>}</main>; }
function Login() { const [mode, setMode] = useState("login"), [form, setForm] = useState({}), [message, setMessage] = useState(""); const navigate = useNavigate(); const submit = e => { e.preventDefault(); api(`/auth/${mode}`, { method: "POST", body: JSON.stringify(form) }).then(x => { localStorage.setItem("token", x.token); navigate("/"); }).catch(x => setMessage(x.message)); }; return <main className="auth"><h1>{mode === "login" ? "Welcome back" : "Create account"}</h1><form onSubmit={submit}>{mode === "register" && <input placeholder="Name" required onChange={e => setForm({ ...form, name: e.target.value })} />}<input placeholder="Email" type="email" required onChange={e => setForm({ ...form, email: e.target.value })} /><input placeholder="Password" type="password" required onChange={e => setForm({ ...form, password: e.target.value })} /><button className="btn">{mode}</button></form><button className="link" onClick={() => setMode(mode === "login" ? "register" : "login")}>Switch to {mode === "login" ? "register" : "login"}</button><p>{message}</p></main>; }
function Bookings() { const [bookings, setBookings] = useState([]); const load = () => api("/bookings").then(setBookings).catch(() => {}); useEffect(load, []); const openQr = async id => { const response = await fetch(`/api/bookings/${id}/qr`, { headers: { Authorization: "Bearer " + localStorage.getItem("token") } }); window.open(URL.createObjectURL(await response.blob()), "_blank"); }; const cancel = id => api(`/bookings/${id}/cancel`, { method: "POST" }).then(load); return <main><h1>My bookings</h1>{bookings.map(b => <article className="row" key={b._id}><div><b>{b.event?.title}</b><p>{b.status} · {new Date(b.createdAt).toLocaleDateString()}</p></div>{b.status === "confirmed" && <><Link className="btn" to={`/tickets/${b._id}`}>Details</Link><button className="btn" onClick={() => openQr(b._id)}>QR code</button><button className="btn" onClick={() => cancel(b._id)}>Cancel</button></>}</article>)}</main>; }
function TicketDetails() { const { id } = useParams(), [ticket, setTicket] = useState(), [qr, setQr] = useState(); useEffect(() => { api(`/bookings/${id}/ticket`).then(setTicket); fetch(`/api/tickets/${id}/qr`, { headers: { Authorization: "Bearer " + localStorage.getItem("token") } }).then(r => r.blob()).then(blob => setQr(URL.createObjectURL(blob))); return () => qr && URL.revokeObjectURL(qr); }, [id]); if (!ticket) return <main>Loading...</main>; return <main className="detail"><h1>{ticket.event.title}</h1><p>Ticket code: <b>{ticket.ticketCode}</b></p><p>Booking {ticket.bookingId} · {ticket.quantity} seat(s)</p><p>{new Date(ticket.event.startAt).toLocaleString()} · {ticket.event.venue}</p>{qr && <img src={qr} alt="Ticket QR code" width="240" height="240" />}</main>; }
function ValidateTicket() { const [code, setCode] = useState(""), [message, setMessage] = useState(""); const submit = e => { e.preventDefault(); api("/tickets/validate", { method: "POST", body: JSON.stringify({ ticketCode: code }) }).then(() => setMessage("VALID TICKET")).catch(error => setMessage(error.message === "Already checked in" ? "TICKET ALREADY USED" : "INVALID TICKET")); }; return <main className="auth"><h1>Validate ticket</h1><form onSubmit={submit}><input placeholder="Ticket code" value={code} onChange={e => setCode(e.target.value)} required /><button className="btn">Validate</button></form>{message && <div className="notice">{message}</div>}</main>; }
function Dashboard() { const [data, setData] = useState(); useEffect(() => { api("/analytics/overview").then(setData).catch(() => {}); }, []); return <main><h1>Organizer dashboard</h1>{data ? <section className="grid"><article className="card"><h3>Events</h3><p>{data.totalEvents}</p></article><article className="card"><h3>Tickets</h3><p>{data.totalTickets}</p></article><article className="card"><h3>Revenue</h3><p>${data.totalRevenue}</p></article><article className="card"><h3>Available seats</h3><p>{data.availableSeats}</p></article></section> : <p>Loading analytics...</p>}</main>; }
function App() { return <><Nav /><Routes><Route path="/" element={<Events />} /><Route path="/events" element={<Events />} /><Route path="/events/:id" element={<EventPage />} /><Route path="/login" element={<Login />} /><Route path="/bookings" element={<Bookings />} /><Route path="/tickets/:id" element={<TicketDetails />} /><Route path="/validate-ticket" element={<ValidateTicket />} /><Route path="/organizer" element={<Dashboard />} /></Routes></>; }
createRoot(document.getElementById("root")).render(<BrowserRouter><App /></BrowserRouter>);
